version: "2"

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:10.3
    container_name: movierama_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /tmp:/tmp
    ports:
      - "25100:5432"
    environment:
      - POSTGRES_PASSWORD=movierama
      - POSTGRES_DB=movierama
      - POSTGRES_USER=movierama

  nginx:
    image: nginx:latest
    container_name: movierama_nginx
    volumes:
      - .:/application
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "8500:80"

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: movierama_php
    volumes:
      - .:/application
